server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: Sarvesh143
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8094/eureka/    