server:
  port: 8093
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: root
    password: Sarvesh143
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
#Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: RATING-SERVICE
  
    
    
    
    #Eureka configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8094/eureka/
      
#      
#      Supose if we want to use configuration from the github or config-server(cloud) then we have to add a dependency
#      of config client(it connects with the config-server like github to fetch application configuration information)
#    then we have to import the configuration in application.yml file, by using 'spring.config.import: optional:configserver: http://localhost:portnumber of configserver'
#i.e 'spring.config.import: url of server'
#to change profile we use spring.profile.active: profilename